site_name: Documentación de desarrollo
nav:
    - Home: index.md
    - lamp/index.md
    - hestiacp/index.md 
    - PiecesPHP Framework: 
        - General: piecesphp/index.md
        - Rutas: piecesphp/content/routing.md
        - Mappers: piecesphp/content/mappers.md
        - Gulp: piecesphp/content/gulp.md
        - Terminal: piecesphp/content/terminal.md
    - performance/index.md
    - tomcat/index.md 
theme:
    name: material
    language: es
    palette:
        scheme: slate
        primary: black
        accent: red
site_dir: ../../docs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
markdown_extensions:
  - attr_list



